---
title: "About"
format: html
editor: visual
---

# Learning Objectives

Through this lesson, you should be able to:

1.  Be familiar with markdown basics.

2.  Know how to cross reference figures and tables.

3.  Explain various types of callout blocks.

4.  Implement code annotation.

5.  Create pdf and presentation slides.

6.  Create a website.

# CPP Farm Store

The Farm Store at Kellogg Ranch, located at AGRIscapes, features a variety of products and novelty items including produce from the campus farm, orchards, nursery, and greenhouses such as:

-   Fresh-squeezed Cal Poly Pomona orange juice

-   Cheese, meats and milk products

-   Cal Poly Pomona grown and locally grown fruits and vegetables

-   Cal Poly Pomona wines and beers

-   100% pure and local honey

-   Grind your own peanut and almond butter

-   Nursery and ornamental crops such as herbs, potted foliage and flowering plants, annuals and perennials, and landscape container plants

-   Gift items include our popular [fruit gift packs](https://www.cpp.edu/farmstore/gift-shop.shtml) and custom gift baskets
