{
  "hash": "42688fab10c4c122d0de18ded3f940f1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Farm Store and Penguins\"\nsubtitle: \"Get Started with Quarto\"\nformat: \n  revealjs:\n    theme: serif\n    smaller: false\n    footer: \"DMC Program Project\"\n    logo: 05_28_20_Center for Customer Insights_Logo_Green Transparent.png\neditor: visual\nexecute: \n  echo: true\nbibliography: references.bib\ncode-annotations: hover\n---\n\n## Farm Store\n\nCPP Farm store has a selected assortment of cool fruits and vegetables right from its on-campus farm.\n\n## Featured Products {.smaller}\n\nIllustration of Multiple columns on a website\n\n::: {layout-ncol=\"2\"}\n![A sample of gift-pack prepared from CPP Grown produce](gift-pack2022.jpg){#fig-gift}\n\n![A sample of wine made from grapes grown right here on campus](2022-hv-zin-rose-755x325.jpg){#fig-wine}\n:::\n\n::::: columns\n::: {.column width=\"50%\"}\nGreat gift for your loved ones. These fruits were raised by students in agriculture majors on CPP campus, processed and packed by student employees at Farm Store.\n:::\n\n::: {.column width=\"50%\"}\nFantastic wine produced right here CPP campus by students!\n:::\n:::::\n\n## Products {.smaller}\n\nUse `panel-tabset` to add multiple tabs to your website.\n\n::: panel-tabset\n### Fruit gift packs\n\n![A Sample of gift-pack prepared from CPP-grown produce](gift-pack2022.jpg)\n\n### Rose Wine\n\n![A sample of wine made from grapes grown right here on campus](2022-hv-zin-rose-755x325.jpg)\n:::\n\nFor the beautiful graphic of fruit gift pack, see @fig-gift.\n\n## Data Preparation {.smaller}\n\nFirst, we need to:\n\n1.  load **packages**\n2.  read in **data**\n3.  check if that data is *in the right format*\n\n[By \"right format\", we mean that the data is tidy, and ready to be summarized and graphed]{.aside}\n\n## Choosing Data\n\n> Penguins are very cute!\n\n... so let's work with penguin data today.\n\n::: callout-note\nFor this analysis we will use the `penguins` dataset from the [palmerpenguins](https://allisonhorst.github.io/palmerpenguins/) package [@gorman2014].\n:::\n\n::: {.callout-caution collapse=\"true\"}\n### Using the data without downloading it\n\nData were collected and made available by Dr. Kristen Gorman and the Palmer Station, Antarctica LTER, a member of the Long Term Ecological Research Network.\n:::\n\n## Loading packages and reading data\n\n::: {.callout-important .smaller}\n### Using the data without downloading it\n\nThis same dataset is also available in the `palmerpenguins` package\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggthemes)\nlibrary(palmerpenguins)\nlibrary(gt)\n```\n:::\n\n## Reading Data \n\n::: {.cell output-location='fragment'}\n\n```{.r .cell-code}\nhead(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n  <fct>   <fct>              <dbl>         <dbl>             <int>       <int>\n1 Adelie  Torgersen           39.1          18.7               181        3750\n2 Adelie  Torgersen           39.5          17.4               186        3800\n3 Adelie  Torgersen           40.3          18                 195        3250\n4 Adelie  Torgersen           NA            NA                  NA          NA\n5 Adelie  Torgersen           36.7          19.3               193        3450\n6 Adelie  Torgersen           39.3          20.6               190        3650\n# ℹ 2 more variables: sex <fct>, year <int>\n```\n\n\n:::\n:::\n\n## Inspecting data \n\n::: {.cell output-location='fragment'}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel…\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse…\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, …\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, …\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186…\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, …\n$ sex               <fct> male, female, female, NA, female, male, female, male…\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…\n```\n\n\n:::\n:::\n\n## Cleaning Data {.smaller}\n\n::: {.cell output-location='fragment'}\n\n```{.r .cell-code}\npenguins |> \n  drop_na() -> penguins_no_na\n\npenguins_no_na\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 333 × 8\n   species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n   <fct>   <fct>              <dbl>         <dbl>             <int>       <int>\n 1 Adelie  Torgersen           39.1          18.7               181        3750\n 2 Adelie  Torgersen           39.5          17.4               186        3800\n 3 Adelie  Torgersen           40.3          18                 195        3250\n 4 Adelie  Torgersen           36.7          19.3               193        3450\n 5 Adelie  Torgersen           39.3          20.6               190        3650\n 6 Adelie  Torgersen           38.9          17.8               181        3625\n 7 Adelie  Torgersen           39.2          19.6               195        4675\n 8 Adelie  Torgersen           41.1          17.6               182        3200\n 9 Adelie  Torgersen           38.6          21.2               191        3800\n10 Adelie  Torgersen           34.6          21.1               198        4400\n# ℹ 323 more rows\n# ℹ 2 more variables: sex <fct>, year <int>\n```\n\n\n:::\n:::\n\n. . .\n\nWe have removed missing values here, which means that the data has now 333 rows. Note that previously there were 344 rows in the original data.[^1]\n\n[^1]: Note that this removes any rows with missing values!\n\n## Code Annotation\n\n``` r\nlibrary(tidyverse)\nlibrary(palmerpenguins)\npenguins |>                                       # <1>\n  mutate(                                         # <2>\n    bill_ratio = bill_depth_mm / bill_length_mm,  # <2>\n    bill_area  = bill_depth_mm * bill_length_mm   # <2>\n  )                                               # <2>\n```\n\n1.  Take `penguins`, and then,\n2.  add new columns for hte bill ratio and bill area.\n\n## Charts by Species \n\n@fig-bi-dims-species is a bar plot of species of penguins.\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\n penguins |> \n   ggplot(aes(bill_length_mm, bill_depth_mm, color = species,\n              shape = species))+\n   geom_point() +\n   theme_minimal() +\n   scale_color_colorblind() +\n   labs(x = \"Bill length (mm)\",\n        y = \"Bill depth (mm)\")\n```\n\n::: {.cell-output-display}\n![Penguin bill dimensions](presentation_files/figure-revealjs/fig-bi-dims-species-1.png){#fig-bi-dims-species fig-alt='A scatterplot of penguins\\' bill depth and length,\ncolored by species of penguins.  There is a strong,\n linear associaiton\n' width=768}\n:::\n:::\n\n## Tables {.smaller}\n\n@tbl-penguins-top10 shows the first 10 penguins from the dataset.\n\n::: {#tbl-penguins-top10 .cell tbl-cap='Top 10 Penguins Sorted by Bill Lengths' output-location='column-fragment'}\n\n```{.r .cell-code .code-overflow-wrap  code-line-numbers=\"|2|4-5\"}\npenguins_no_na |> \n  slice_head(n = 10) |> \n  select(species, island, bill_length_mm, bill_depth_mm) |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"cvmzwweaka\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#cvmzwweaka table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#cvmzwweaka thead, #cvmzwweaka tbody, #cvmzwweaka tfoot, #cvmzwweaka tr, #cvmzwweaka td, #cvmzwweaka th {\n  border-style: none;\n}\n\n#cvmzwweaka p {\n  margin: 0;\n  padding: 0;\n}\n\n#cvmzwweaka .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#cvmzwweaka .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#cvmzwweaka .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#cvmzwweaka .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#cvmzwweaka .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cvmzwweaka .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cvmzwweaka .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cvmzwweaka .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#cvmzwweaka .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#cvmzwweaka .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#cvmzwweaka .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#cvmzwweaka .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#cvmzwweaka .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#cvmzwweaka .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#cvmzwweaka .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#cvmzwweaka .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#cvmzwweaka .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#cvmzwweaka .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#cvmzwweaka .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cvmzwweaka .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#cvmzwweaka .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#cvmzwweaka .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#cvmzwweaka .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cvmzwweaka .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#cvmzwweaka .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#cvmzwweaka .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cvmzwweaka .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cvmzwweaka .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#cvmzwweaka .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cvmzwweaka .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#cvmzwweaka .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cvmzwweaka .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cvmzwweaka .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cvmzwweaka .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cvmzwweaka .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cvmzwweaka .gt_left {\n  text-align: left;\n}\n\n#cvmzwweaka .gt_center {\n  text-align: center;\n}\n\n#cvmzwweaka .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#cvmzwweaka .gt_font_normal {\n  font-weight: normal;\n}\n\n#cvmzwweaka .gt_font_bold {\n  font-weight: bold;\n}\n\n#cvmzwweaka .gt_font_italic {\n  font-style: italic;\n}\n\n#cvmzwweaka .gt_super {\n  font-size: 65%;\n}\n\n#cvmzwweaka .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#cvmzwweaka .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#cvmzwweaka .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#cvmzwweaka .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#cvmzwweaka .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#cvmzwweaka .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#cvmzwweaka .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#cvmzwweaka .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#cvmzwweaka div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"species\">species</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"island\">island</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bill_length_mm\">bill_length_mm</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bill_depth_mm\">bill_depth_mm</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"species\" class=\"gt_row gt_center\">Adelie</td>\n<td headers=\"island\" class=\"gt_row gt_center\">Torgersen</td>\n<td headers=\"bill_length_mm\" class=\"gt_row gt_right\">39.1</td>\n<td headers=\"bill_depth_mm\" class=\"gt_row gt_right\">18.7</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_center\">Adelie</td>\n<td headers=\"island\" class=\"gt_row gt_center\">Torgersen</td>\n<td headers=\"bill_length_mm\" class=\"gt_row gt_right\">39.5</td>\n<td headers=\"bill_depth_mm\" class=\"gt_row gt_right\">17.4</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_center\">Adelie</td>\n<td headers=\"island\" class=\"gt_row gt_center\">Torgersen</td>\n<td headers=\"bill_length_mm\" class=\"gt_row gt_right\">40.3</td>\n<td headers=\"bill_depth_mm\" class=\"gt_row gt_right\">18.0</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_center\">Adelie</td>\n<td headers=\"island\" class=\"gt_row gt_center\">Torgersen</td>\n<td headers=\"bill_length_mm\" class=\"gt_row gt_right\">36.7</td>\n<td headers=\"bill_depth_mm\" class=\"gt_row gt_right\">19.3</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_center\">Adelie</td>\n<td headers=\"island\" class=\"gt_row gt_center\">Torgersen</td>\n<td headers=\"bill_length_mm\" class=\"gt_row gt_right\">39.3</td>\n<td headers=\"bill_depth_mm\" class=\"gt_row gt_right\">20.6</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_center\">Adelie</td>\n<td headers=\"island\" class=\"gt_row gt_center\">Torgersen</td>\n<td headers=\"bill_length_mm\" class=\"gt_row gt_right\">38.9</td>\n<td headers=\"bill_depth_mm\" class=\"gt_row gt_right\">17.8</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_center\">Adelie</td>\n<td headers=\"island\" class=\"gt_row gt_center\">Torgersen</td>\n<td headers=\"bill_length_mm\" class=\"gt_row gt_right\">39.2</td>\n<td headers=\"bill_depth_mm\" class=\"gt_row gt_right\">19.6</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_center\">Adelie</td>\n<td headers=\"island\" class=\"gt_row gt_center\">Torgersen</td>\n<td headers=\"bill_length_mm\" class=\"gt_row gt_right\">41.1</td>\n<td headers=\"bill_depth_mm\" class=\"gt_row gt_right\">17.6</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_center\">Adelie</td>\n<td headers=\"island\" class=\"gt_row gt_center\">Torgersen</td>\n<td headers=\"bill_length_mm\" class=\"gt_row gt_right\">38.6</td>\n<td headers=\"bill_depth_mm\" class=\"gt_row gt_right\">21.2</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_center\">Adelie</td>\n<td headers=\"island\" class=\"gt_row gt_center\">Torgersen</td>\n<td headers=\"bill_length_mm\" class=\"gt_row gt_right\">34.6</td>\n<td headers=\"bill_depth_mm\" class=\"gt_row gt_right\">21.1</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n## How to post online {.smaller}\n\n1.  Create your content in Quarto. You need at least three documents\n\n    1.  index.qmd\n\n    2.  another qmd file\n\n    3.  \"\\_quarto.yml\" created in Text File.\n\n2.  Reload the4 project from the upper-right-hand corner. After this, you should see the \"build\" tab appear next to the environment tab.\n\n3.  Click \"Render website\" and confirm that you have a website with all the files combined.\n\n4.  Now it is time to publish\n\n    1.  Move to the terminal next to \"Console\" tab.\n\n    2.  Type \"quarto publish quarto-pub\" and follow the instructions on the pane.\n\n    3.  Go to your quarto-pub website and find it.\n\n## Resources {.smaller}\n\n-   Authoring: <https://quarto.org/docs/authoring/markdown-basics.html>\n-   Creating a website: <https://quarto.org/docs/websites/>\n-   [Quarto Gallery](https://quarto.org/docs/websites/)\n\n------------------------------------------------------------------------\n\n-   Get started with Quarto \\| Mine Cetinkaya-Rundel: {{< video https://www.youtube.com/watch?v=_f3latmOhew >}}\n\n------------------------------------------------------------------------\n\n-   Quarto for Academics | Mine Çetinkaya-Rundel: {{< video https://www.youtube.com/watch?v=EbAAmrB0luA&t=112s >}}\n\n## References\n",
    "supporting": [
      "presentation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}